import 'dart:ui';
import 'package:flutter/material.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.whiteA70001,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: appTheme.gray50,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: appTheme.whiteA70001,
            width: 2,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(28),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      checkboxTheme: CheckboxThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        side: BorderSide(
          width: 1,
        ),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 2,
        space: 2,
        color: appTheme.gray50001,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.black90001,
          fontSize: 16,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w300,
        ),
        bodyMedium: TextStyle(
          color: appTheme.black90001,
          fontSize: 15,
          fontFamily: 'DM Sans',
          fontWeight: FontWeight.w400,
        ),
        displayLarge: TextStyle(
          color: appTheme.whiteA70001,
          fontSize: 52,
          fontFamily: 'Lilita One',
          fontWeight: FontWeight.w400,
        ),
        displayMedium: TextStyle(
          color: appTheme.whiteA70001,
          fontSize: 44,
          fontFamily: 'Lilita One',
          fontWeight: FontWeight.w400,
        ),
        displaySmall: TextStyle(
          color: appTheme.green600,
          fontSize: 36,
          fontFamily: 'DM Sans',
          fontWeight: FontWeight.w700,
        ),
        headlineLarge: TextStyle(
          color: appTheme.whiteA70001,
          fontSize: 30,
          fontFamily: 'DM Sans',
          fontWeight: FontWeight.w700,
        ),
        headlineSmall: TextStyle(
          color: appTheme.black90001.withOpacity(0.6),
          fontSize: 24,
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w500,
        ),
        labelLarge: TextStyle(
          color: appTheme.black90001,
          fontSize: 12,
          fontFamily: 'Inter',
          fontWeight: FontWeight.w500,
        ),
        labelMedium: TextStyle(
          color: appTheme.black90001,
          fontSize: 10,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w600,
        ),
        titleLarge: TextStyle(
          color: appTheme.black90001,
          fontSize: 20,
          fontFamily: 'DM Sans',
          fontWeight: FontWeight.w500,
        ),
        titleMedium: TextStyle(
          color: appTheme.gray50003,
          fontSize: 16,
          fontFamily: 'DM Sans',
          fontWeight: FontWeight.w500,
        ),
        titleSmall: TextStyle(
          color: appTheme.black90001,
          fontSize: 15,
          fontFamily: 'Poppins',
          fontWeight: FontWeight.w500,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0X872DBF42),
    primaryContainer: Color(0XFF22256C),

    // Error colors
    errorContainer: Color(0XFF595959),
    onError: Color(0XFFE97D00),
    onErrorContainer: Color(0XFF060B05),

    // On colors(text colors)
    onPrimary: Color(0XFF0008D6),
    onPrimaryContainer: Color(0XFFF3E6B7),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber
  Color get amber100 => Color(0XFFF3E6B6);

  // Black
  Color get black900 => Color(0XFF0F0F0F);
  Color get black90001 => Color(0XFF000000);

  // Blue
  Color get blue900 => Color(0XFF0B1CB3);

  // BlueGray
  Color get blueGray100 => Color(0XFFD9D9D9);
  Color get blueGray50 => Color(0XFFEFF0F6);
  Color get blueGray500 => Color(0XFF6E6B8F);
  Color get blueGray900 => Color(0XFF170F49);
  Color get blueGray90001 => Color(0XFF292D32);

  // BlueGrayC
  Color get blueGray100C1 => Color(0XC1DAD7D7);

  // DeepOrange
  Color get deepOrange600 => Color(0XFFFA5914);
  Color get deepOrangeA10063 => Color(0X63F8A06F);

  // DeepPurple
  Color get deepPurple900 => Color(0XFF0C13C0);

  // GrayF
  Color get gray100F4 => Color(0XF4F7F5F5);
  Color get gray900F2 => Color(0XF21E1E1E);

  // GrayB
  Color get gray200B7 => Color(0XB7EFECEC);

  // Gray
  Color get gray400 => Color(0XFFB6B0B0);
  Color get gray40001 => Color(0XFFAEAEAE);
  Color get gray50 => Color(0XFFFAFAFA);
  Color get gray500 => Color(0XFFB2A8A8);
  Color get gray50001 => Color(0XFF959494);
  Color get gray50002 => Color(0XFFA39B9B);
  Color get gray50003 => Color(0XFF979393);
  Color get gray600 => Color(0XFF726C6C);
  Color get gray700 => Color(0XFF625D5D);
  Color get gray70001 => Color(0XFF675353);
  Color get gray800 => Color(0XFF413E31);
  Color get gray90011 => Color(0X11121141);

  // Grayf
  Color get gray9000f => Color(0X0F080F34);

  // Green
  Color get green20030 => Color(0X30ACD3AB);
  Color get green600 => Color(0XFF28C925);
  Color get greenA700 => Color(0XFF0DEA16);
  Color get greenA70001 => Color(0XFF04EC00);

  // GreenB
  Color get green300B7 => Color(0XB779E577);

  // GreenAa
  Color get green800Aa => Color(0XAA259D1A);

  // Indigo
  Color get indigoA100 => Color(0XFF9D96F2);

  // IndigoAEd
  Color get indigoA200Ed => Color(0XED606DE6);

  // IndigoAd
  Color get indigoA7002d => Color(0X2D4939FF);

  // LightGreen
  Color get lightGreenA700 => Color(0XFF49F13B);
  Color get lightGreenA70001 => Color(0XFF3FEA45);
  Color get lightGreenA70002 => Color(0XFF78F83D);

  // Lime
  Color get lime900 => Color(0XFF7C9000);

  // Orange
  Color get orangeA200 => Color(0XFFDF8E43);
  Color get orangeA20001 => Color(0XFFEC923F);
  Color get orangeA20002 => Color(0XFFE69245);

  // Pink
  Color get pink300 => Color(0XFFFE627F);

  // Purplef
  Color get purple5007f => Color(0X7FAF02BE);

  // Purple
  Color get purpleA200 => Color(0XFFEC31F0);
  Color get purpleA700 => Color(0XFFA103EC);

  // Red
  Color get red30075 => Color(0X75CD8849);
  Color get red50 => Color(0XFFFCF0F0);
  Color get red600 => Color(0XFFEF3232);
  Color get redA700 => Color(0XFFF50E0E);
  Color get redA70001 => Color(0XFFEC0000);
  Color get redA70002 => Color(0XFFCB0707);

  // TealAB
  Color get tealA100B2 => Color(0XB2B3FAED);

  // White
  Color get whiteA700 => Color(0XFFFDFDFD);
  Color get whiteA70001 => Color(0XFFFFFFFF);

  // Yellow
  Color get yellowA400 => Color(0XFFEEF308);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
